### ISSUE TITLE
Is there a way to force frzr to re-deploy a current version?

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/frzr#14]
Somehow I borked my gamer-os install in the sense that my flatpak kodi installation no longer can access any of my nfs hosted media library. 
I'm guessing this was do to me using frzr-unlock and trying to install some thing manually via pacman. 

Can I somehow force frzr-deploy to re-deploy the current release of gamer-os?

**Comment by ChojinDSL** [comment]
I booted a rescue usb, renamed the btrfs subvolume in frzr_root/deployments to something else, added that name to the relevant places in the fstab and syslinux.cfg. Then I rebooted and the auto update mechanism took care of the rest.

Unfortunately that did not fix my issue. I had to uninstall kodi, wipe the /home/gamer/.var/app/tv.kodi.tv folder and then reinstall the flatpak image. 
Strangely enough it seems that now the flatpak gets installed to a different directory.

**Comment by ChojinDSL** [comment]
Weird, looks like kodi now is in the .var directory. Oh well, re-configure everything again.

**Comment by alkazar** [comment]
This is not currently possible because the subvolume names cannot be changed. This appears to be a limitation of btrfs subvolumes or the way the subvolume import/export works.

The only work around is to install a previous version, reboot, then install the new version. This is obviously not great.

Another possibility would be to have some kind of recovery option in the installer. In that case, since the system would not be booted into GamerOS you could delete the subvolume and redownload it.

**Comment by ChojinDSL** [comment]
What do you mean, subvolume names can't be changed? You can just rename a subvolume with "mv"
e.g. mv old_subvolume new_subvolume. Or do you mean something else?

**Comment by alkazar** [comment]
You can't rename the existing subvolume because the system would stop working.
You can't change the location to which you extract the new subvolume because btrfs doesn't let you. You would first have to extract it to the same location, which would fail because a subvolume already exists.

**Comment by ChojinDSL** [comment]
Ah ok, I booted a rescue USB so that the gamer os wasn't running. Then I just mounted the partition and did the aforementioned steps.
